server:
  port: 8081

spring:
  application:
    name: consolidation-service

  # Configuração do Banco de Dados PostgreSQL (Consolidação)
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fluxocaixa}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Configuração de conexão com o RabbitMQ
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 1000ms
          max-attempts: 3
          multiplier: 2.0

  # Formatação padrão de datas no JSON de resposta
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd

# Mapeamento de propriedades de mensageria lidas pelo RabbitMQConfig e ConsolidationService
mq:
  queues:
    transaction-consolidation: transaction.consolidation.queue

# Observabilidade e Métrica (Spring Boot Actuator & Prometheus)
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
