server:
  port: 8080

spring:
  application:
    name: transaction-service

  # Configuração do Banco de Dados PostgreSQL (Lançamentos)
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fluxocaixa}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Configuração de conexão com o RabbitMQ
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 3
        multiplier: 2.0

  # Formatação padrão de datas no JSON das requisições e respostas
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd

# Mapeamento de propriedades de mensageria lidas pelo RabbitMQConfig e TransactionService
mq:
  exchanges:
    transaction: transaction.exchange
  queues:
    transaction-consolidation: transaction.consolidation.queue
  routing-keys:
    transaction-created: transaction.created

# Observabilidade e Métricas (Spring Boot Actuator & Prometheus)
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
